### ISSUE TITLE
cytofclean missing?

### ISSUE THREAD

**Issue by mdmanurung** [JimboMahoney/CyTOF-Template-Creator#15]
Dear `JimboMahoney`,

I am sure that you used to have a repo named `cytofclean`. I would like to use it again, but I cannot find it now. Is it still available somewhere? I know this is unrelated to this repo, but I cannot think of other means of contacting you.

Thanks in advance.

Regards,
Mikhael

**Comment by JimboMahoney** [comment]
Hi Mikhael,

Sorry about that - I wasn't sure if anyone was using it and as I no longer work in cytometry, I removed it as I may not be able to fix / improve it from now on.

It should be back again now.
