### ISSUE TITLE
Disconnected from the server error

### ISSUE THREAD

**Issue by AlexanderSchmitz-GitHub** [JimboMahoney/CyTOF-Template-Creator#16]
Hi, I have tried to upload a template (.tem), but it fails. 
The App states "upload complete", but also "disconnected from server - Reload". Any after reloading the page is back at the default template stage. Any ideas ?
Best regards
Alexander

**Comment by JimboMahoney** [comment]
Can you share the template file with me? Maybe something's changed in the CyTOF software with the generation of the template file.

**Comment by AlexanderSchmitz-GitHub** [comment]
I don't think so. It even does not work to re-upload the downloaded temp file for the DIP, created with the shiny app and then downloaded. 
I will try from home. Maybe it is a security problem from the server here....

**Comment by JimboMahoney** [comment]
Heya,

I'm seeing the same issue - i.e. when uploading from a template file generated by CyTOF, so I'll take a look at why it's breaking...

**Comment by JimboMahoney** [comment]
Sorry! This was totally my fault - I left some code in for local testing, which causes an issue on the server!

Should be fixed now!

(Apologies - I don't work with flow / mass cytometry any more, so I'm not using this functionality any more, although my ex-colleagues might be!)
